services:
  evrinoma.soap.manager:
    class: Evrinoma\SoapBundle\Manager\SoapManager
    autowire: true

  Evrinoma\SoapBundle\Manager\SoapManager:
    alias: evrinoma.soap.manager

  evrinoma.soap.controller:
    class: Evrinoma\SoapBundle\Controller\SoapController
    autowire: true

  Evrinoma\SoapBundle\Controller\SoapController:
    alias: evrinoma.soap.controller
    public: true

  evrinoma.soap.listener.subscriber:
    class: Evrinoma\SoapBundle\Subscriber\SoapAnnotationSubscriber
    arguments:
      - '@annotations.reader'
    tags:
      - { name: kernel.event_subscriber }

  Evrinoma\SoapBundle\Subscriber\SoapAnnotationSubscriber:
    alias: evrinoma.soap.listener.subscriber
    public: true

