services:
  evrinoma.soap.manager:
    class: Evrinoma\SoapBundle\Manager\SoapManager
    autowire: true

  Evrinoma\SoapBundle\Manager\SoapManager:
    alias: evrinoma.soap.manager

  evrinoma.soap.controller:
    class: Evrinoma\SoapBundle\Controller\SoapController
    autowire: true

  Evrinoma\SoapBundle\Controller\SoapController:
    alias: evrinoma.soap.controller
    public: true

  evrinoma.soap.api.controller:
    class: Evrinoma\SoapBundle\Controller\SoapApiController
    autowire: true

  Evrinoma\SoapBundle\Controller\SoapApiController:
    alias: evrinoma.soap.api.controller
    public: true

  evrinoma.discovery.manager:
    class: Evrinoma\SoapBundle\Discovery\CustomAutoDiscovery
    autowire: true

  Evrinoma\SoapBundle\Discovery\CustomAutoDiscovery:
    alias: evrinoma.discovery.manager