services:
  evrinoma.soap.manager:
    alias: Evrinoma\SoapBundle\Manager\SoapManager

  Evrinoma\SoapBundle\Manager\SoapManagerInterface:
    alias: Evrinoma\SoapBundle\Manager\SoapManager

  Evrinoma\SoapBundle\Manager\SoapManager:
    arguments:
      - '@request_stack'
      - '@evrinoma.redis.cache'
#      - '@evrinoma.file.cache'

  evrinoma.soap.controller:
    class: Evrinoma\SoapBundle\Controller\SoapController
    autowire: true

  Evrinoma\SoapBundle\Controller\SoapController:
    alias: evrinoma.soap.controller
    public: true

  evrinoma.file.cache:
    class:  Evrinoma\SoapBundle\Cache\FileCache
    autowire: true

  evrinoma.redis.cache:
    class: Evrinoma\SoapBundle\Cache\RedisCache
    autowire: true

  Evrinoma\SoapBundle\Cache\FileCache:
    alias: evrinoma.file.cache
    public: true

  Evrinoma\SoapBundle\Cache\RedisCache:
    alias: evrinoma.redis.cache
    public: true

