services:
  evrinoma.soap.manager:
    alias: Evrinoma\SoapBundle\Manager\SoapManager

  Evrinoma\SoapBundle\Manager\SoapManagerInterface:
    alias: Evrinoma\SoapBundle\Manager\SoapManager

  Evrinoma\SoapBundle\Manager\SoapManager:
    arguments:
      - '@request_stack'

  evrinoma.soap.controller:
    class: Evrinoma\SoapBundle\Controller\SoapController
    autowire: true

  Evrinoma\SoapBundle\Controller\SoapController:
    alias: evrinoma.soap.controller
    public: true

