services:
  evrinoma.soap.manager:
    class: Evrinoma\SoapBundle\Manager\SoapManager
    arguments:
      - '@evrinoma.discovery.manager'
      - '@request_stack'

  Evrinoma\SoapBundle\Manager\SoapManager:
    alias: evrinoma.soap.manager

  evrinoma.soap.controller:
    class: Evrinoma\SoapBundle\Controller\SoapController
    autowire: true

  Evrinoma\SoapBundle\Controller\SoapController:
    alias: evrinoma.soap.controller
    public: true

  evrinoma.soap.api.controller:
    class: Evrinoma\SoapBundle\Controller\SoapApiController
    arguments:
      - '@jms_serializer'
      - '@evrinoma.soap.manager'
    autowire: true

  Evrinoma\SoapBundle\Controller\SoapApiController:
    alias: evrinoma.soap.api.controller
    public: true

  evrinoma.discovery.manager:
    class: Evrinoma\SoapBundle\Discovery\CustomAutoDiscovery
    arguments:
      - '@annotations.reader'

  Evrinoma\SoapBundle\Discovery\CustomAutoDiscovery:
    alias: evrinoma.discovery.manager
